apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive-metastore.name" . }}
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}

spec:
  {{ .Values.service.type }}

  selector:
    {{- include "hive-metastore.selectorLabels" . | nindent 4 }}